# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'login_mfa.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


import time
from PyQt5 import QtCore, QtGui, QtWidgets

import sys


class LoginWindow:
    def __init__(self, app, has_account):
        self.app = app
        self.qtApp = QtWidgets.QApplication(sys.argv)

        self.login_window = QtWidgets.QMainWindow()
        self.setupUi(self.login_window)
        self.login_window.show()

        sys.exit(self.qtApp.exec())

    def setupUi(self, login_window):
        login_window.setObjectName("login_window")
        login_window.resize(360, 200)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(login_window.sizePolicy().hasHeightForWidth())
        login_window.setSizePolicy(sizePolicy)
        login_window.setMinimumSize(QtCore.QSize(320, 200))
        login_window.setMaximumSize(QtCore.QSize(16777215, 140))
        self.centralwidget = QtWidgets.QWidget(login_window)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.connect_btn = QtWidgets.QPushButton(self.centralwidget)
        self.connect_btn.setMinimumSize(QtCore.QSize(0, 50))
        self.connect_btn.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.connect_btn.setObjectName("connect_btn")
        self.connect_btn.clicked.connect(self.connect_btn_onclick)

        self.gridLayout.addWidget(self.connect_btn, 1, 0, 1, 3)
        self.account_lb = QtWidgets.QLabel(self.centralwidget)
        self.account_lb.setObjectName("account_lb")
        self.gridLayout.addWidget(self.account_lb, 0, 0, 1, 1)
        self.account_input = QtWidgets.QLineEdit(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.account_input.sizePolicy().hasHeightForWidth())
        self.account_input.setSizePolicy(sizePolicy)
        self.account_input.setMinimumSize(QtCore.QSize(0, 0))
        self.account_input.setObjectName("account_input")
        self.gridLayout.addWidget(self.account_input, 0, 1, 1, 2)
        login_window.setCentralWidget(self.centralwidget)

        self.retranslateUi(login_window)
        QtCore.QMetaObject.connectSlotsByName(login_window)

    def retranslateUi(self, login_window):
        _translate = QtCore.QCoreApplication.translate
        login_window.setWindowTitle(_translate("login_window", "login_window"))
        self.connect_btn.setText(_translate("login_window", "Connect"))
        self.account_lb.setText(_translate("login_window", "Email account:"))

    

    def connect_btn_onclick(self):
        self.app.clear_auth()
        self.dialog = QtWidgets.QDialog()
        child = LoginDialog(self.app, self.login_window)
        child.setupUi(self.dialog)
        self.login_window.hide()
        # time.sleep(1)
        child.set_prompt()
        self.dialog.exec()
        
            


class LoginDialog(object):
    def __init__(self, app, parent):
        self.app = app
        self.parent = parent
        self.app.try_connect()

    def setupUi(self, dialog):
        self.window = dialog
        self.window.setObjectName("Dialog")
        self.window.resize(360, 200)
        self.prompt_lb = QtWidgets.QLabel(self.window)
        self.prompt_lb.setGeometry(QtCore.QRect(30, 40, 281, 101))
        self.prompt_lb.setCursor(QtGui.QCursor(QtCore.Qt.IBeamCursor))
        self.prompt_lb.setObjectName("prompt_lb")
        self.prompt_lb.setWordWrap(True)
        self.prompt_lb.setTextInteractionFlags(QtCore.Qt.TextSelectableByMouse)

        self.back_btn = QtWidgets.QPushButton(self.window)
        self.back_btn.setGeometry(QtCore.QRect(0, 0, 41, 41))
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("left-arrow.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.back_btn.setIcon(icon1)
        self.back_btn.setIconSize(QtCore.QSize(35, 30))
        self.back_btn.setObjectName("back_btn")
        self.back_btn.clicked.connect(self.back_btn_onclick)

        self.retranslateUi(self.window)
        QtCore.QMetaObject.connectSlotsByName(self.window)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Please follow the instruction"))

    def set_prompt(self):
        if not hasattr(self.app, 'flow'):
            self.prompt_lb.setText('Waiting for response...')
            self.con_timer = QtCore.QTimer()
            self.con_timer.timeout.connect(self.set_prompt)  # execute `display_time`
            self.con_timer.setInterval(5)
            self.con_timer.start()
        else:
            self.auth_timer = QtCore.QTimer()
            self.prompt_lb.setText(self.app.flow["message"])
            self.auth_timer.timeout.connect(self.detect_auth) # to main window
            self.auth_timer.setInterval(1)
            self.auth_timer.start()

    def detect_auth(self):
        if self.app.token:
            self.dashborad_window = QtWidgets.QMainWindow()
            self.dashborad = Dashboard(self.app)
            self.dashborad.setupUi(self.dashborad_window)

            self.window.done(self.window.Accepted)
            self.dashborad_window.show()
            
        else:
            self.auth_timer = QtCore.QTimer()
            self.auth_timer.timeout.connect(self.detect_auth) # to main window
            self.auth_timer.setInterval(1)
            self.auth_timer.start()


    def back_btn_onclick(self):
        if hasattr(self.app, 'flow'):
            self.app.flow['expires_at'] = 0
        self.window.done(self.window.Accepted)
        self.parent.show()

    
class Dashboard(object):
    def __init__(self, app):
        self.app = app
        self.current_selected_tab_1 = None
        self.total_submission = None
        self.next_due_date = None
        self.total_review = None
        self.total_rating = None
        self.total_students = None
        self.server_email_address = None
        self.connection_status = None

    def setupUi(self, dashboard):
        dashboard.setObjectName("Dashboard")
        dashboard.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(dashboard)
        self.centralwidget.setObjectName("centralwidget")
        # Create a tabwidget
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(0, 0, 841, 611))
        self.tabWidget.setObjectName("tabWidget")
        # Create our first tab
        self.tab_main = QtWidgets.QWidget()
        self.tab_main.setObjectName("tab_main")
        # Create objects for tab_main
        # Label used to show the current server's connection status
        self.label_1 = QtWidgets.QLabel(self.tab_main)
        self.label_1.setGeometry(QtCore.QRect(540, 10, 260, 21))
        self.label_1.setStyleSheet("font: 18pt \".AppleSystemUIFont\";")
        self.label_1.setObjectName("label_1")
        # Label used to show the total submisstions/reviews/ratings for the current deadline
        self.label_2 = QtWidgets.QLabel(self.tab_main)
        self.label_2.setGeometry(QtCore.QRect(0, 60, 800, 21))
        self.label_2.setStyleSheet("font: 18pt \".AppleSystemUIFont\";")
        self.label_2.setObjectName("label_2")
        self.label_2.setAlignment(QtCore.Qt.AlignLeft)
        # Label used to show the next due date
        self.label_3 = QtWidgets.QLabel(self.tab_main)
        self.label_3.setGeometry(QtCore.QRect(0, 80, 800, 21))
        self.label_3.setStyleSheet("font: 18pt \".AppleSystemUIFont\";")
        self.label_3.setObjectName("label_3")
        # Label used to show the total students
        self.label_4 = QtWidgets.QLabel(self.tab_main)
        self.label_4.setGeometry(QtCore.QRect(0, 100, 800, 21))
        self.label_4.setStyleSheet("font: 18pt \".AppleSystemUIFont\";")
        self.label_4.setObjectName("label_4")
        # CombBox which contains "Sbumission/Review/Rating"
        self.comboBox = QtWidgets.QComboBox(self.tab_main)
        self.comboBox.setGeometry(QtCore.QRect(80, 0, 111, 51))
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        # Label for the CombBox
        self.label_5 = QtWidgets.QLabel(self.tab_main)
        self.label_5.setGeometry(QtCore.QRect(0, 10, 81, 21))
        self.label_5.setStyleSheet("font: 18pt \".AppleSystemUIFont\";")
        self.label_5.setObjectName("label_5")
        # Binding events to the function
        self.comboBox.currentTextChanged.connect(self.on_changed_combobox_tab_1)
        # PushButton. User can click on it and change the server status. (Connected/Disconnected)
        self.pushButton = QtWidgets.QPushButton(self.tab_main)
        self.pushButton.setGeometry(QtCore.QRect(600, 471, 120, 51))
        self.pushButton.setStyleSheet("color: rgb(74, 255, 14);")
        self.pushButton.setObjectName("pushButton")
        self.pushButton.clicked.connect(self.on_clicked_button_tab_1)
        # Add tab_main to the tabWidget
        self.tabWidget.addTab(self.tab_main, "")
        # Create tab_students_details
        self.tab_students_details = QtWidgets.QWidget()
        self.tab_students_details.setObjectName("tab_students_details")
        # Add tab_students_details to the tabWidget
        self.tabWidget.addTab(self.tab_students_details, "")
        dashboard.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(dashboard)
        self.statusbar.setObjectName("statusbar")
        dashboard.setStatusBar(self.statusbar)

        self.retranslateUi(dashboard)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(dashboard)

    def retranslateUi(self, dashboard):
        _translate = QtCore.QCoreApplication.translate
        dashboard.setWindowTitle(_translate("Dashboard", "Dashboard"))
        self.label_1.setText(_translate("Dashboard", f"Current Status: {self.connection_status}"))
        self.label_2.setText(_translate("Dashboard", f"Students submission submitted for current deadline: {self.total_submission}"))
        self.label_3.setText(_translate("Dashboard", f"Next Due Date: {self.next_due_date}"))
        self.label_4.setText(_translate("Dashboard", f"Total Students: {self.total_students}"))
        self.comboBox.setItemText(0, _translate("Dashboard", "Submission"))
        self.comboBox.setItemText(1, _translate("Dashboard", "Review"))
        self.comboBox.setItemText(2, _translate("Dashboard", "Rating"))
        self.label_5.setText(_translate("Dashboard", "Deadline:"))

        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_main), _translate("Dashboard", "Main"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_students_details), _translate("Dashboard", "Students Details"))
    
    def on_changed_combobox_tab_1(self, selected_value):
        print("Combbox changed", selected_value)
        if selected_value == "Submission":
            self.label_2.setText(f"Students submissions submitted for current deadline: {self.total_submission}")
        elif selected_value == "Review":
            self.label_2.setText(f"Students reviews submitted for current deadline: {self.total_review}")
        elif selected_value == "Rating":
            self.label_2.setText(f"Students ratings submitted for current deadline: {self.total_rating}")

    def on_clicked_button_tab_1(self):
        if not self.app.token:
            self.connection_status = "Disconnected"

            # If disconnected. Token exist
            self.label_1.setText(f"Current Status: {self.connection_status}")
            self.pushButton.setText("Connect")
            self.label_1.setStyleSheet("color: rgb(255, 43, 32);font: 18pt \".AppleSystemUIFont\";")
            self.pushButton.setStyleSheet("color: rgb(74, 255, 14);")
        elif self.app.token:
            # If connected
            self.label_1.setText(f"Current Status: {self.connection_status}")
            self.label_1.setGeometry(QtCore.QRect(540, 10, 200, 21))
            self.label_1.setStyleSheet("color: rgb(255, 43, 32);font: 18pt \".AppleSystemUIFont\";")
            self.pushButton.setStyleSheet("color: rgb(255, 43, 32);")
        print("button cliecked")
        



