# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'deadlines.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(538, 138)
        self.gridLayout_2 = QtWidgets.QGridLayout(Dialog)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.review_dtedit = QtWidgets.QDateTimeEdit(Dialog)
        self.review_dtedit.setObjectName("review_dtedit")
        self.gridLayout.addWidget(self.review_dtedit, 2, 1, 1, 1)
        self.timezone_combobox = QtWidgets.QComboBox(Dialog)
        self.timezone_combobox.setObjectName("timezone_combobox")
        self.gridLayout.addWidget(self.timezone_combobox, 1, 3, 1, 1)
        self.label_4 = QtWidgets.QLabel(Dialog)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 3, 0, 1, 1)
        self.label_6 = QtWidgets.QLabel(Dialog)
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 0, 3, 1, 1)
        self.subm_id_lb = QtWidgets.QLabel(Dialog)
        self.subm_id_lb.setAlignment(QtCore.Qt.AlignCenter)
        self.subm_id_lb.setObjectName("subm_id_lb")
        self.gridLayout.addWidget(self.subm_id_lb, 0, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 1)
        self.subm_dtedit = QtWidgets.QDateTimeEdit(Dialog)
        self.subm_dtedit.setObjectName("subm_dtedit")
        self.gridLayout.addWidget(self.subm_dtedit, 1, 1, 1, 1)
        self.eval_dtedit = QtWidgets.QDateTimeEdit(Dialog)
        self.eval_dtedit.setObjectName("eval_dtedit")
        self.gridLayout.addWidget(self.eval_dtedit, 3, 1, 1, 1)
        self.label_3 = QtWidgets.QLabel(Dialog)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 2, 0, 1, 1)
        self.line = QtWidgets.QFrame(Dialog)
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.gridLayout.addWidget(self.line, 0, 2, 4, 1)
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayout, 0, 0, 1, 1)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Schedule"))
        self.label_4.setText(_translate("Dialog", "Evaluation Deadline"))
        self.label_6.setText(_translate("Dialog", "Time Zone"))
        self.subm_id_lb.setText(_translate("Dialog", "1"))
        self.label_2.setText(_translate("Dialog", "Submission Deadline (Distribution Time)"))
        self.label_3.setText(_translate("Dialog", "Review Deadline"))
        self.label.setText(_translate("Dialog", "Submission ID"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
