# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/student_detail.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(831, 638)
        Dialog.setWindowTitle("")
        self.gridLayout_2 = QtWidgets.QGridLayout(Dialog)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.addr_lb = QtWidgets.QLabel(Dialog)
        self.addr_lb.setObjectName("addr_lb")
        self.gridLayout.addWidget(self.addr_lb, 0, 0, 1, 1)
        self.bottom_left_tb = QtWidgets.QTableWidget(Dialog)
        self.bottom_left_tb.setObjectName("bottom_left_tb")
        self.bottom_left_tb.setColumnCount(0)
        self.bottom_left_tb.setRowCount(0)
        self.gridLayout.addWidget(self.bottom_left_tb, 6, 0, 1, 1)
        self.top_right_tb = QtWidgets.QTableWidget(Dialog)
        self.top_right_tb.setObjectName("top_right_tb")
        self.top_right_tb.setColumnCount(0)
        self.top_right_tb.setRowCount(0)
        self.gridLayout.addWidget(self.top_right_tb, 3, 2, 1, 1)
        self.label_4 = QtWidgets.QLabel(Dialog)
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 3, 1, 1, 1)
        self.label_3 = QtWidgets.QLabel(Dialog)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 6, 1, 1, 1)
        self.bottom_right_tb = QtWidgets.QTableWidget(Dialog)
        self.bottom_right_tb.setObjectName("bottom_right_tb")
        self.bottom_right_tb.setColumnCount(0)
        self.bottom_right_tb.setRowCount(0)
        self.gridLayout.addWidget(self.bottom_right_tb, 6, 2, 1, 1)
        self.top_textedit = QtWidgets.QTextEdit(Dialog)
        self.top_textedit.setObjectName("top_textedit")
        self.gridLayout.addWidget(self.top_textedit, 2, 2, 1, 1)
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 2, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 5, 0, 1, 1)
        self.bottom_textedit = QtWidgets.QTextEdit(Dialog)
        self.bottom_textedit.setObjectName("bottom_textedit")
        self.gridLayout.addWidget(self.bottom_textedit, 5, 2, 1, 1)
        self.top_left_tb = QtWidgets.QTableWidget(Dialog)
        self.top_left_tb.setObjectName("top_left_tb")
        self.top_left_tb.setColumnCount(0)
        self.top_left_tb.setRowCount(0)
        self.gridLayout.addWidget(self.top_left_tb, 3, 0, 1, 1)
        self.line = QtWidgets.QFrame(Dialog)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.gridLayout.addWidget(self.line, 4, 2, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayout, 0, 0, 1, 1)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        self.addr_lb.setText(_translate("Dialog", "example@gmail.com"))
        self.label_4.setText(_translate("Dialog", "is reviewed by"))
        self.label_3.setText(_translate("Dialog", "also reviewed by"))
        self.label.setText(_translate("Dialog", "Student has submitted:"))
        self.label_2.setText(_translate("Dialog", "has reviewed:"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
